// This file is automatically generated or custom-updated.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let token: string | undefined;

    try {
      // 1. Try standard Supabase session retrieval first
      const { data } = await supabase.auth.getSession();
      token = data.session?.access_token;
    } catch (e) {
      console.error('[Auth Attacher] Error getting session:', e);
    }

    // 2. Fallback for Capacitor mobile webview race conditions on cold start
    if (!token && typeof window !== 'undefined') {
      try {
        const storageKey = 'sb-rftmcmetkvrwwokswhgc-auth-token';
        const rawToken = window.localStorage.getItem(storageKey);
        if (rawToken) {
          const parsed = JSON.parse(rawToken);
          token = parsed?.access_token;
        }
      } catch (err) {
        console.error('[Auth Attacher] Fallback localStorage read failed:', err);
      }
    }

    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)